### ISSUE TITLE
Support mapping flat result set to object hierarchy

### ISSUE THREAD

**Issue by testpossessed** [SqlRepo/sqlrepo#10]
Currently SqlRepo only supports mapping to root entity from result set.  We need to provide a mechanism to let entity mappers know how to map column values in result rows to a typed member or a collection of types.

**Comment by testpossessed** [comment]
The only implementation of IEntityMapper we have a the moment is for a DataReader.  I was thinking our first type mapping implementation should be a simple index mapper.  Also propose we create a fluent builder for the mapping.  Basically it would work by mapping index n to a member of a type that is attached to the root entity or is in a child collection of the root entity.  Working on an example.

**Comment by testpossessed** [comment]
Having made an attempt at this I think it is going to be too complex and seriously impact performance.

Too complex because we would need to cater for every type of query a developer might construct and that logic is likely to hit performance quite badly.

So I propose we drop this idea and just provide plenty of examples of how to populate an object graph.

**Comment by MarkioE** [comment]
Understood and agree.
