### ISSUE TITLE
Add IConnectionProvider

### ISSUE THREAD

**Issue by testpossessed** [SqlRepo/SqlRepo#11]
Instead of requiring a connection string provide IConnectionProvider interface and provide some implementations for common scenarios.  The idea being instead of specifying the connection string at the repository or command level a provider can be instantiated or injected allowing much broader support for connecting to data sources.

**Comment by testpossessed** [comment]
Faustina is working on this now.  We need to consider whether we make it a breaking change and remove the current method of passing the connection string to Go or support both.

My preference would be to make it a breaking change and bump the version to 2.0.0.

Thoughts?

**Comment by MarkioE** [comment]
With this new way of specifying the connection string I don't see the benefit of having it in the Go method. It feels counter-intuitive to supply a connection string at the end of creating the SQL statement.

If there are more breaking changes in the pipeline it would be good to have a v2 pre-release branch which we can start basing the documentation off.

**Comment by testpossessed** [comment]
Been thinking about this one with knowledge of how it has been implemented so far.

So with my agreement/guidance IConnectionProvider can currently only be set once during initial setup of a RepositoryFactory whether through IoC or the static RepoFactory pending release.

My thoughts started drifting towards usage and wondered whether we should stretch this to support passing a connection provider to a Repository or even to a Statement (@mark Commands have been renamed to statements to avoid conflict with adaptors around SqlConnection and SqlCommand).

I was particularly thinking of situations where one might want use multiple databases in a single application.  So we could setup the RepositoryFactory with a connection provider for the most commonly used database but override it at lower levels.

So for example we might have something like:

```
myRepo.Using(db1ConnectionProvider).Query()...;
mySelectStatement.....Using(db2ConnectionProvider).Go();

```

**Comment by MarkioE** [comment]
The scenario you describe is exactly how I use SqlRepo in one of our applications. The main application uses a single connection string heavily, and then for one side task I am connecting to another database containing extra information which I pull across.

I like what you suggest. I can have my standard connection provider, but I can also have a new interface ICustomerDatabaseConnectionProvider which inherits from IConnectionProvider. This can be injected and passed to the myRepo.Using() method.

**Comment by MarkioE** [comment]
Actually what I suggested above might not work as the IOC container, I believe, will use the last registered IConnectionProvider when creating the RepositoryFactory.

**Comment by testpossessed** [comment]
It depends on how it is registered and injected.  If the alternate was given a unique interface and injected using that interface into the class that was overriding the provider it would work.

How to setup these providers in IoC is something we have to document.  We can’t include them in the existing modules.
