### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by MarkioE** [SqlRepo/sqlrepo#12]
Something to consider is supporting transactions with SqlConnection.BeginTransaction().

https://msdn.microsoft.com/en-us/library/86773566(v=vs.110).aspx

**Comment by testpossessed** [comment]
Do we need to do anything specifically with Transactions.  Given we use SqlSconnection internally, transactions are already supported with a TransactionScope

https://msdn.microsoft.com/en-us/library/system.transactions.transactionscope(v=vs.110).aspx

**Comment by MarkioE** [comment]
I don't think we need to do much, but I would like to be able to run multiple queries in one transaction and able to roll back. I think this is as simple as exposing the ability to start and end a transaction from an instance of IRepositoryFactory.

**Comment by testpossessed** [comment]
I think you can already do that using transaction scope.  If your commands are all executed within

```csharp
using(var scope = new TransactionScope())
{
    ...execute command here
}
```
They will be executed in a single transaction and you can rollback the scope and everything in it will be rolled back.

Given the way the commands delegate to a CommandExecutor you don't have the connection to create the transaction from.  So hard to see how we could it from the factory level.

**Comment by MarkioE** [comment]
Fantastic, that looks like it will do the job!

**Comment by testpossessed** [comment]
Definitely worth testing out and documenting sooner rather than later

**Comment by MarkioE** [comment]
Tested and confirmed it works as expected. I will write the Wiki page for it later.

**Comment by testpossessed** [comment]
Cool, we can close this one then
