### ISSUE TITLE
Build Script In Source Repo

### ISSUE THREAD

**Issue by testpossessed** [SqlRepo/sqlrepo#13]
Investigate whether we can include a build script in source control and get appveyor to use it.  At the moment it is a pain having to edit the script online every time we add a new project

**Comment by testpossessed** [comment]
Think this might be as simple as exporting the .yaml file and including it in source control

**Comment by testpossessed** [comment]
So we can export the yaml from AppVeyor and keep it in the repo but it would then include an encrypted version of the NuGet API Key.  Not sure if this is a problem but possibly.  Looking at what we can do to secure the yml file and only make it available to specific people

**Comment by testpossessed** [comment]
Looking into having two builds one to handle CI build, test and packaging.  The second to handle deployment of packages.  That way we can have the yaml file in source control for the CI build to avoid the need to go to AppVeyor for adding new projects into the process.

**Comment by testpossessed** [comment]
Finally found information on AppVeyor about secure strings.  It seems a unique encryption key is created for each account so even if someone took they encrypted key from a yaml file in the repo they could not use it within a different account.  So it seems it is safe to keep the exported .yml file in our repo to make life easier for contributors to the project.

Mark are you ok with us having the encrypted NuGet API key in the repo?

**Comment by MarkioE** [comment]
That's fine by me. The API key is restricted to the SqlRepo.* pattern.

**Comment by testpossessed** [comment]
Cool will do that now
