### ISSUE TITLE
Data Reader Performance Improvements

### ISSUE THREAD

**Issue by MarkioE** [SqlRepo/sqlrepo#23]

**Comment by MarkioE** [comment]
I have created a new class **EntityActivator** which can be used to create new instances of the TEntity using a lambda function. This creates a bit of dynamic IL for better perf. See https://rogerjohansson.blog/2008/02/28/linq-expressions-creating-objects/

Changed how we set the properties on the created TEntity. See https://stackoverflow.com/questions/17660097/is-it-possible-to-speed-this-method-up/17669142#17669142

Final change was to check the types of the properties we are trying to map and instead of using DataReader.GetValue we are using the relevant method (such as GetString or GetDecimal) which will reduce boxing / unboxing.

Initial performance benchmarks show a huge improvement, I'll get a PR in today.

**Comment by testpossessed** [comment]
Excellent, great work

**Comment by MarkioE** [comment]
Initial improvements done so I will close this. I'm sure there will be more we can do in future.
