### ISSUE TITLE
NSubstitue testing extensions

### ISSUE THREAD

**Issue by testpossessed** [SqlRepo/sqlrepo#27]
Incorporate existing NSubstitute extensions for testing statements

**Comment by testpossessed** [comment]
@MarkioE Just noticed there is a project with this code in, but it is called FluentAssertions.  To avoid confusion I am going to rename it as it doesn't use FluentAssertions even though it has a dependency

**Comment by MarkioE** [comment]
@testpossessed Sure, I hate naming things :)
