### ISSUE TITLE
Register NoOpSqlLogger with all IOC projects

### ISSUE THREAD

**Issue by MarkioE** [SqlRepo/SqlRepo#43]

**Comment by testpossessed** [comment]
I didn't do this intentionally.  It is used in the static repo factory when no other is provided.  I think in all other cases it needs to be up to the developer to prepare and register the ISqlLogger they want to use including the noop version if they want to use it.

**Comment by testpossessed** [comment]
We should probably document that in the IoC pages

**Comment by MarkioE** [comment]
I only put this in because I added the modules and expected it to run on a new project and it threw me for a while trying to figure out why it wasn't working. Perhaps an exception when we try to use the logger?

**Comment by testpossessed** [comment]
I am not sure any code would make it to any checks.  I think the first time SqlRepo is used we would get an exception from Autofac as it will be unable to create an instance to inject into StatementFactoryProvider, which is itself injected into RepositoryFactory.

If we want to ensure at least one logger is registered we would need to change things such that the dependency is on multiple loggers and we ensure the noop version is registered.

To make this elegant I suggest we provide an implementation of ISqlLogger that we do register in the IoC modules, but it in turn has a dependency on IEnumerable<ISqlLogWriter>.  The existing ISqlLogger implementations become ISqlLogWriter implementations.  This way we can register the noop logger in our IoC modules whilst allowing developers to create or use others.  Our new concrete SqlLogger would loop through all ISqlLogWriter implementations that are injected and delegate to them to do the actual logging.

What do you think?

**Comment by MarkioE** [comment]
That is normally the approach I take when creating log writers so I'm happy with that. I can pick this one up.
