### ISSUE TITLE
Both demos have errors

### ISSUE THREAD

**Issue by AzThinker** [SqlRepo/SqlRepo#47]
1、The database of two demos， lacks Doit table;
2、Two demos, lack of System.Configuration.ConfigurationManager, System.Data.SqlClient references；
3、The class Program of GettingStartedStatic should add：RepoFactory.UseLogger(new NoOpSqlLogger());

**Comment by testpossessed** [comment]
Thanks for the feedback, I am on holiday for the next couple of weeks so will be able to look at that and improving the demos.  We haven’t given them as much attention as we wanted.

**Comment by testpossessed** [comment]
Will have a think about license and drop one into the repo, but it will be very open

**Comment by testpossessed** [comment]
Replaced previous demos with new similar ones for each IoC container we provide packages for.
