### ISSUE TITLE
Add IServiceCollection Registration NuGet Package

### ISSUE THREAD

**Issue by MarkioE** [SqlRepo/sqlrepo#9]
This task is to create a new NuGet package containing an extension method to register all of the types with the Microsoft IServiceCollection dependency injection.

Already done in a side project so I will take this one.

**Comment by testpossessed** [comment]
Cool, makes sense to provide different IoC registration modules as we go.  I may have to do one for NInject soon as we use that at Clarksons.

**Comment by MarkioE** [comment]
This is done but for some reason the version number did not get written by AppVeyor. Is there an extra step I must take? @testpossessed

**Comment by testpossessed** [comment]
Did you do it on a branch.  I changed the appveyor build to only build and deploy from master so we can use feature branches and PRs

**Comment by MarkioE** [comment]
It is on master. It built + deployed the NuGet package but version is 1.0.0.0

**Comment by testpossessed** [comment]
Sorry I saw it was on master after that question, also looked at AppVeyor build and can see you have added the two statements needed to build it so not sure what is going wrong, trying to remember what else I did

**Comment by testpossessed** [comment]
Appveyor, still looking at my personal branch so have changed that, not sure it is the problem though

**Comment by testpossessed** [comment]
That didn't work, not sure what is happening there all looks like it should work to me

**Comment by testpossessed** [comment]
Found it, the problem is there is no version element in the new .csproj file so it is not getting patched. I am assuming because the version in properties is still the default of 1.0.0.0.  All the other projects were changed to 1.0.16.0 at some point.

I've updated the version and push the change so should sort itself out soon

**Comment by testpossessed** [comment]
Worked :-)

**Comment by MarkioE** [comment]
Thanks!
